type Summoner {
  region: Region!
  accountId: String!
  profileIconId: Int!
  revisiondate: Int!
  name: String!
  id: String!
  puuid: String!
  summonerLevel: Int!
  matchlist(filter: MatchListInput): MatchList!
}
