name: Check for breaking changes
on:
  workflow_dispatch:
    inputs:
      schema_url:
        description: 'Remote Schema'
  schedule:
    - cron: "0 1 * * *"

env:
  default_url: "http://www.mingweisamuel.com/riotapi-schema/openapi-3.0.0.json"
  latestSchema: latestSchema.json
  currentSchema: currentSchema.json
        
jobs:        
  fetch_latest_schema:
    name: "fetch latest riot api openapi schema"
    runs-on: ubuntu-latest
    steps:
      - name: get latest Schema
        run: curl ${{ github.events.input.schema_url }} --output ${{ env.latestSchema }} || curl ${{ env.default_url }} --output ${{ env.latestSchema }}
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: latestSchema
          path: ${{ env.latestSchema }}
    
  comp_diff: 
    name: 'diff schemas'
    runs-on: ubuntu-latest
    needs: fetch_latest_schema
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.0

      - name: install openapi-diff
        run: npm i openapi-diff
        
      - name: Checkout
        uses: actions/checkout@v2.3.1      
        
      - name: get currently used schema
        run: node .github/workflows/scripts/getUsedSchema.js > ${{ env.currentSchema }}
      
      - name: download latest schema artifact
        uses: actions/download-artifact@v2
        with: 
          name: latestSchema
        
      - name: diff schemas
        run: | 
          npx openapi-diff ${{ env.currentSchema }} latestSchema.json | grep "\"breakingDifferences\"" || exit 0
        continue-on-error: true
        
      - name: fail if breaking changes
        if: failure()
        run: |
          echo "::error::Breaking Differences in api update"
          exit 1

  generate_report:
    name: "generate report of used and unused endpoints"
    needs: fetch_latest_schema
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.0
      
      - name: checkout
        uses: actions/checkout@v2.3.1
      
      - name: download latest schema artifact
        uses: actions/download-artifact@v2
        with:
          name: latestSchema
      
      - name: install packages
        run: npm i typescript ts-node swagger-parser
      
      - name: generate report 
        run: |
          node .github/workflows/scripts/getUsedSchema.js > ${{ env.currentSchema }}
          npx openapi-diff ${{ env.currentSchema }} ${{ env.latestSchema }} >> report.txt
          npm run find-unused-endpoints |  grep -zo "Implemented:.*" >> report.txt
          echo "::debug::${cat report.txt}"
      
      - name: upload report
        uses: actions/upload-artifact@v2
        with: 
          name: report.txt
          path: report.txt
