name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Remote Schema'
        required: true
        default: 'http://www.mingweisamuel.com/riotapi-schema/openapi-3.0.0.json'


jobs:        
  comp_diff: 
    name: 'comp_diff of openapi schema'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.0

      - name: install openapi-diff
        run: npm i openapi-diff
        
      - name: Checkout
        uses: actions/checkout@v2.3.1      
        
      - name: get currently used schema
        run: node .github/workflows/scripts/getUsedSchema.js > usedSchema.json
      
      - name: output full diff
        run: npx openapi-diff usedSchema.json ${{ env.name }} 
        
      - name: diff shchemas
        run: |
          res=$(npx openapi-diff usedSchema.json http://www.mingweisamuel.com/riotapi-schema/openapi-3.0.0.json | grep "\"breakingDifferencesFound\": false" -)
          echo $res
          echo "::set-env name=res::${res}"
      
      - name: check for breaking diffs
        if: contains(env.res, '"breakingDifferencesFound:\ false"') 
        run: exit 0
     
      - name: breaking diff
        run: exit 1
        
        
