type Query {
  info: Info!
  summoner(
    region: RegionInput!
    encryptedAccountId: String
    summonerName: String
    encryptedPUUID: String
    encryptedSummonerId: String
  ): Summonerv4Summoner
  match(region: RegionInput!, matchId: MatchId!, game: Game!): Match
  rankedList(
    region: RegionInput!
    queue: Queue!
    tier: LowerTier!
    division: Division
    page: Int
    game: Game!
  ): [Leaguev4LeagueList!]!
  rankedLeague(tier: Tier, leagueId: String, game: Game!): Leaguev4LeagueEntry!
  tournament(code: String!): Tournamentv4TournamentCode
  tournamentStub(code: String!): TournamentStub!
  """
  Get featured league games.
  note! game parameter is ignored atm
  """
  featuredGames(
    region: RegionInput!
    game: Game = League
  ): Spectatorv4FeaturedGames
  championRotation: Championv3ChampionInfo!
  clash: String
}

# TODO: valorant match, lor match
union Match = Matchv4Match | Tftmatchv1Match

scalar MatchId

enum RegionInput {
  br1
  eun1
  euw1
  jp1
  kr
  la1
  la2
  na1
  oc1
  tr1
  ru
  americas
  asia
  europe
}

enum Game {
  League
  TFT
  "LOR is not fully implemented"
  LOR
  # TODO valorant endponts?
  # Valorant
}

enum UpperTier {
  CHALLENGER
  GRANDMASTER
  MASTER
}

enum LowerTier {
  DIAMOND
  PLATINUM
  GOLD
  SILVER
  BRONZE
  IRON
  UNRANKED
}

enum AllRankedQueues {
  RANKED_SOLO_5X5
  RANKED_TFT
  RANKED_FLEX_SR
  RANKED_FLEX_TT
}

enum Division {
  I
  II
  III
  IV
}
scalar Long

type Info {
  description: String!
  version: String
  constants: String
  repo: String
}

type TournamentStub {
  lobbyEvents: [Tournamentv4LobbyEvent!]!
}
